export enum IdPaese {
    AF = 'AF', // Afghanistan
    AX = 'AX', // Isole Åland
    AL = 'AL', // Albania
    DZ = 'DZ', // Algeria
    AS = 'AS', // Samoa Americane
    AD = 'AD', // Andorra
    AO = 'AO', // Angola
    AI = 'AI', // Anguilla
    AQ = 'AQ', // Antartide
    AG = 'AG', // Antigua e Barbuda
    AR = 'AR', // Argentina
    AM = 'AM', // Armenia
    AW = 'AW', // Aruba
    AU = 'AU', // Australia
    AT = 'AT', // Austria
    AZ = 'AZ', // Azerbaigian
    BS = 'BS', // Bahamas
    BH = 'BH', // Bahrein
    BD = 'BD', // Bangladesh
    BB = 'BB', // Barbados
    BY = 'BY', // Bielorussia
    BE = 'BE', // Belgio
    BZ = 'BZ', // Belize
    BJ = 'BJ', // Benin
    BM = 'BM', // Bermuda
    BT = 'BT', // Bhutan
    BO = 'BO', // Bolivia
    BQ = 'BQ', // Isole BES
    BA = 'BA', // Bosnia ed Erzegovina
    BW = 'BW', // Botswana
    BV = 'BV', // Isola Bouvet
    BR = 'BR', // Brasile
    IO = 'IO', // Territori Britannici dell'Oceano Indiano
    BN = 'BN', // Brunei
    BG = 'BG', // Bulgaria
    BF = 'BF', // Burkina Faso
    BI = 'BI', // Burundi
    KH = 'KH', // Cambogia
    CM = 'CM', // Camerun
    CA = 'CA', // Canada
    CV = 'CV', // Capo Verde
    KY = 'KY', // Isole Cayman
    CF = 'CF', // Repubblica Centrafricana
    TD = 'TD', // Ciad
    CL = 'CL', // Cile
    CN = 'CN', // Cina
    CX = 'CX', // Isola del Natale
    CC = 'CC', // Isole Cocos e Keeling
    CO = 'CO', // Colombia
    KM = 'KM', // Comore
    CG = 'CG', // Congo
    CD = 'CD', // Repubblica Democratica del Congo
    CK = 'CK', // Isole Cook
    CR = 'CR', // Costa Rica
    CI = 'CI', // Costa d'Avorio
    HR = 'HR', // Croazia
    CU = 'CU', // Cuba
    CW = 'CW', // Curaçao
    CY = 'CY', // Cipro
    CZ = 'CZ', // Cechia
    DK = 'DK', // Danimarka
    DJ = 'DJ', // Gibuti
    DM = 'DM', // Dominica
    DO = 'DO', // Repubblica Dominicana
    EC = 'EC', // Ecuador
    EG = 'EG', // Egitto
    SV = 'SV', // El Salvador
    GQ = 'GQ', // Guinea Equatoriale
    ER = 'ER', // Eritrea
    EE = 'EE', // Estonia
    ET = 'ET', // Etiopia
    FK = 'FK', // Isole Falkland
    FO = 'FO', // Isole Fær Øer
    FJ = 'FJ', // Figi
    FI = 'FI', // Finlandia
    FR = 'FR', // Francia
    GF = 'GF', // Guyana Francese
    PF = 'PF', // Polinesia Francese
    TF = 'TF', // Territori Francesi del Sud
    GA = 'GA', // Gabon
    GM = 'GM', // Gambia
    GE = 'GE', // Georgia
    DE = 'DE', // Germania
    GH = 'GH', // Ghana
    GI = 'GI', // Gibilterra
    GR = 'GR', // Grecia
    GL = 'GL', // Groenlandia
    GD = 'GD', // Grenada
    GP = 'GP', // Guadalupa
    GU = 'GU', // Guam
    GT = 'GT', // Guatemala
    GG = 'GG', // Guernsey
    GN = 'GN', // Guinea
    GW = 'GW', // Guinea-Bissau
    GY = 'GY', // Guyana
    HT = 'HT', // Haiti
    HM = 'HM', // Isole Heard e McDonald
    VA = 'VA', // Città del Vaticano
    HN = 'HN', // Honduras
    HK = 'HK', // Hong Kong
    HU = 'HU', // Ungheria
    IS = 'IS', // Islanda
    IN = 'IN', // India
    ID = 'ID', // Indonesia
    IR = 'IR', // Iran
    IQ = 'IQ', // Iraq
    IE = 'IE', // Irlanda
    IM = 'IM', // Isola di Man
    IL = 'IL', // Israele
    IT = 'IT', // Italia
    JM = 'JM', // Giamaica
    JP = 'JP', // Giappone
    JE = 'JE', // Jersey
    JO = 'JO', // Giordania
    KZ = 'KZ', // Kazakistan
    KE = 'KE', // Kenya
    KI = 'KI', // Kiribati
    KP = 'KP', // Corea del Nord
    KR = 'KR', // Corea del Sud
    KW = 'KW', // Kuwait
    KG = 'KG', // Kirghizistan
    LA = 'LA', // Laos
    LV = 'LV', // Lettonia
    LB = 'LB', // Libano
    LS = 'LS', // Lesotho
    LR = 'LR', // Liberia
    LY = 'LY', // Libia
    LI = 'LI', // Liechtenstein
    LT = 'LT', // Lituania
    LU = 'LU', // Lussemburgo
    MO = 'MO', // Macao
    MK = 'MK', // Macedonia
    MG = 'MG', // Madagascar
    MW = 'MW', // Malawi
    MY = 'MY', // Malesia
    MV = 'MV', // Maldive
    ML = 'ML', // Mali
    MT = 'MT', // Malta
    MH = 'MH', // Isole Marshall
    MQ = 'MQ', // Martinica
    MR = 'MR', // Mauritania
    MU = 'MU', // Mauritius
    YT = 'YT', // Mayotte
    MX = 'MX', // Messico
    FM = 'FM', // Micronesia
    MD = 'MD', // Moldavia
    MC = 'MC', // Monaco
    MN = 'MN', // Mongolia
    ME = 'ME', // Montenegro
    MS = 'MS', // Montserrat
    MA = 'MA', // Marocco
    MZ = 'MZ', // Mozambico
    MM = 'MM', // Birmania
    NA = 'NA', // Namibia
    NR = 'NR', // Nauru
    NP = 'NP', // Nepal
    NL = 'NL', // Paesi Bassi
    NC = 'NC', // Nuova Caledonia
    NZ = 'NZ', // Nuova Zelanda
    NI = 'NI', // Nicaragua
    NE = 'NE', // Niger
    NG = 'NG', // Nigeria
    NU = 'NU', // Niue
    NF = 'NF', // Isole Norfolk
    MP = 'MP', // Isole Marianne Settentrionali
    NO = 'NO', // Norvegia
    OM = 'OM', // Oman
    PK = 'PK', // Pakistan
    PW = 'PW', // Palau
    PS = 'PS', // Stato di Palestina
    PA = 'PA', // Panama
    PG = 'PG', // Papua Nuova Guinea
    PY = 'PY', // Paraguay
    PE = 'PE', // Perù
    PH = 'PH', // Filippine
    PN = 'PN', // Isole Pitcairn
    PL = 'PL', // Polonia
    PT = 'PT', // Portogallo
    PR = 'PR', // Porto Rico
    QA = 'QA', // Qatar
    RE = 'RE', // Réunion
    RO = 'RO', // Romania
    RU = 'RU', // Russia
    RW = 'RW', // Ruanda
    BL = 'BL', // Saint-Barthélemy
    SH = 'SH', // Sant'Elena, Isola di Acensione e Tristan da Cunha
    KN = 'KN', // Saint Kitts e Nevis
    LC = 'LC', // Santa Lucia
    MF = 'MF', // Saint-Martin
    PM = 'PM', // Saint-Pierre e Miquelon
    VC = 'VC', // Saint Vincent e Grenadine
    WS = 'WS', // Samoa
    SM = 'SM', // San Marino
    ST = 'ST', // Sao Tome e Principe
    SA = 'SA', // Arabia Saudita
    SN = 'SN', // Senegal
    RS = 'RS', // Serbia
    SC = 'SC', // Seychelles
    SL = 'SL', // Sierra Leone
    SG = 'SG', // Singapore
    SX = 'SX', // Sint Maarten
    SK = 'SK', // Slovacchia
    SI = 'SI', // Slovenia
    SB = 'SB', // Isole Solomon
    SO = 'SO', // Somalia
    ZA = 'ZA', // Sud Africa
    GS = 'GS', // Georgia del Sud e Isole Sandwich meridionali
    SS = 'SS', // Sudan del Sud
    ES = 'ES', // Spagna
    LK = 'LK', // Sri Lanka
    SD = 'SD', // Sudan
    SR = 'SR', // Suriname
    SJ = 'SJ', // Svalbard e Jan Mayen
    SZ = 'SZ', // Swaziland
    SE = 'SE', // Svezia
    CH = 'CH', // Svizzera
    SY = 'SY', // Siria
    TW = 'TW', // Taiwan (Repubblica di Cina
    TJ = 'TJ', // Tagikistan
    TZ = 'TZ', // Tanzania
    TH = 'TH', // Tailandia
    TL = 'TL', // Timor Est
    TG = 'TG', // Togo
    TK = 'TK', // Tokelau
    TO = 'TO', // Tonga
    TT = 'TT', // Trinidad e Tobago
    TN = 'TN', // Tunisia
    TR = 'TR', // Turchia
    TM = 'TM', // Turkmenistan
    TC = 'TC', // Isole Turks e Caicos
    TV = 'TV', // Tuvalu
    UG = 'UG', // Uganda
    UA = 'UA', // Ucraina
    AE = 'AE', // Emirati Arabi Uniti
    GB = 'GB', // Regno Unito
    US = 'US', // Stati Uniti
    UM = 'UM', // Isole Minor Esterne degli Stati Uniti
    UY = 'UY', // Uruguay
    UZ = 'UZ', // Uzbekistan
    VU = 'VU', // Vanuatu
    VE = 'VE', // Venezuela
    VN = 'VN', // Vietnam
    VG = 'VG', // Isole Vergini britanniche
    VI = 'VI', // Isole Vergini americane
    WF = 'WF', // Wallis e Futuna
    EH = 'EH', // Sahara Occidentale
    YE = 'YE', // Yemen
    ZM = 'ZM', // Zambia
    ZW = 'ZW', // Zimbabwe
}
